name: "RandomBaselineBDA"
model_type: "MaskedTower"
model: "MaskedRandomBaseline"
task: "BDA"
input:
  normalized_inputs: true
  mask_inputs: true
validation:
  validation_parameters:
    batch_size: 1
    validation_monitor: "val_macro_iou"
    validation_monitor_mode: "max"
    validation_checkpoint_save_top_k: 3
    validation_reduce_lr_on_plateau_patience: 3
    validation_reduce_lr_on_plateau_cooldown: 3
training:
  training_parameters:
    gradient_clip_val: 10.0
    batch_size: 1
    grad_accumulation: 8
    l1_reg: 1.0e-06
    l2_reg: 1.0e-05
    log_images_every_n_steps: 100
    mask_x: 2048
    mask_y: 2048
    max_epochs: 100
    optimizer_parameters:
      name: "AdamW"
      lr: 0.0005
      weight_decay: 0.00001
    output_class_weights_strategy: "ipw"
    normalize_weights: False
    output_class_weights:
      background: 1
      destroyed: 1
      major damage: 1
      minor damage: 1
      no damage: 1
      un-classified: 1
    samples_per_epoch: 4000
    tile_x: 2048
    tile_y: 2048
    loss_parameters:
      loss: [["cross entropy", 1.0]]
      gamma: 2
      alpha: 0.25
      bins: 10
      momentum: 0.9
      smooth: 1.0e-06