import os
import argparse
import yaml

# Task -> the validation monitor that TaskModuleBase.configure_checkpoint()/configure_optimizers()
# will look for. BDA/RDA log "val_macro_f1"; the BDAADJ alignment task logs an IoU instead.
TASK_MONITORS = {
    "BDA": "val_macro_f1",
    "RDA": "val_macro_f1",
    "BDAADJ": "val_ortho_inference_avg_IoU",
}

GENERATED_HEADER = (
    "# Template model hyperparameters file generated by create_hyperparameters_file.py.\n"
    "# This uses the current top-level schema (model_type/model/task/input/training/validation/\n"
    "# model_parameters) that train.py and infer.py load - NOT the legacy input-nested schema.\n"
    "#\n"
    "# This is only a starting point. Before it will actually train you must at minimum:\n"
    "#   * fill in model_parameters for your architecture (copy from a sibling config under\n"
    "#     Models/<Model>/hyperparameters/),\n"
    "#   * confirm model_type/model (or encoder_type/decoder_type) match model_registry.py, and\n"
    "#   * pair it at run time with the separate channel-map and sample-generator YAMLs\n"
    "#     (channels no longer live in this file - see data_envs/Tasks/<TASK>/Channels/).\n"
)


def build_hyperparameters(task, model_type, model, name, class_weights):
    task_base = task.split("-")[0].upper()  # "RDA-full" -> "RDA"
    monitor = TASK_MONITORS.get(task_base, "val_macro_f1")

    training_parameters = {
        "batch_size": 1,
        "grad_accumulation": 16,
        "max_epochs": 1000,
        "gradient_clip_val": 10.0,
        "l1_reg": 1.0e-07,
        "l2_reg": 1.0e-06,
        "log_images_every_n_steps": 100,
        "tile_x": 2048,
        "tile_y": 2048,
        "mask_x": 2048,
        "mask_y": 2048,
        "normalize_weights": False,
        "optimizer_parameters": {
            "name": "AdamW",
            "lr": 0.0001,
            "weight_decay": 1.0e-05,
        },
        "loss_parameters": {
            "loss": [["cross entropy", 1.0]],
            "gamma": 2,
            "alpha": 0.25,
            "bins": 10,
            "momentum": 0.9,
            "smooth": 1.0e-06,
        },
    }

    # Class weights are consumed via output_class_weights_strategy. If the caller supplied an
    # explicit weights file, embed it as the "manual" strategy; otherwise default to "ipw", which
    # derives weights from observed class counts and needs no inline table.
    if class_weights:
        training_parameters["output_class_weights_strategy"] = "manual"
        training_parameters["output_class_weights"] = class_weights
    else:
        training_parameters["output_class_weights_strategy"] = "ipw"

    hyperparameters = {
        "name": name,
        "model_type": model_type,
        "task": task_base,
        "input": {
            "normalized_inputs": True,
            "mask_input": True,
        },
        "training": {"training_parameters": training_parameters},
        "validation": {
            "validation_parameters": {
                "batch_size": 1,
                "validation_monitor": monitor,
                "validation_monitor_mode": "max",
                "validation_checkpoint_save_top_k": 3,
                "validation_reduce_lr_on_plateau_patience": 5,
                "validation_reduce_lr_on_plateau_cooldown": 3,
                # End training early if validation_monitor stops improving for this many epochs.
                # Set to 0 (or remove) to disable the guard. See TaskModuleBase.configure_early_stopping().
                "validation_early_stopping_patience": 12,
            }
        },
        # Fill this in per-architecture (see Models/<Model>/hyperparameters/ for real examples).
        "model_parameters": {},
    }

    # Tower/MaskedTower select a network via "model"; EncoderDecoder variants use
    # encoder_type/decoder_type instead (see model_registry.py).
    if "EncoderDecoder" in model_type:
        hyperparameters["encoder_type"] = "ViT"
        hyperparameters["decoder_type"] = "UperNet"
    else:
        hyperparameters["model"] = model

    return hyperparameters


def main():
    parser = argparse.ArgumentParser(
        description="Create a template model hyperparameters file (current train.py/infer.py schema)."
    )
    parser.add_argument(
        "--out_path",
        type=str,
        help="The path to folder where the hyperparameters file should be saved to.",
        default="./",
    )
    parser.add_argument(
        "--task",
        type=str,
        help="The task for the model. For RDA, the variant suffix is accepted but ignored here "
             "(e.g. RDA-full -> task: RDA); the variant only selects the channel-map file.",
        default="BDA",
    )
    parser.add_argument(
        "--model_type",
        type=str,
        help="Model wrapper type from model_registry.py "
             "(Tower, MaskedTower, EncoderDecoder, MaskedEncoderDecoder).",
        default="MaskedTower",
    )
    parser.add_argument(
        "--model",
        type=str,
        help="For Tower/MaskedTower types, the model key from model_registry.py "
             "(e.g. MaskedUNetTowerModule). Ignored for EncoderDecoder types.",
        default="MaskedUNetTowerModule",
    )
    parser.add_argument(
        "--name",
        type=str,
        help="The 'name' field for the generated config (used in checkpoint/log names).",
        default=None,
    )
    parser.add_argument(
        "--class_weights_file",
        type=str,
        help="Optional path to a YAML mapping output class -> weight. When provided, it is embedded "
             "as the 'manual' output_class_weights_strategy; otherwise the template defaults to 'ipw'.",
        default=None,
    )
    parser.add_argument(
        "--channel_maps_file",
        type=str,
        help="DEPRECATED and ignored. Channel maps now live in their own file passed at run time "
             "via --channels_hyperparameters_file_path (see data_envs/Tasks/<TASK>/Channels/).",
        default=None,
    )
    args = parser.parse_args()

    if args.channel_maps_file:
        print("WARNING: --channel_maps_file is deprecated and ignored. Channel maps are no longer "
              "embedded in the model hyperparameters file; pass them at run time via "
              "--channels_hyperparameters_file_path (see data_envs/Tasks/<TASK>/Channels/).")

    class_weights = None
    if args.class_weights_file:
        with open(args.class_weights_file, "r") as file:
            class_weights = yaml.safe_load(file)

    name = args.name if args.name else (args.task + "_template")
    hyperparameters = build_hyperparameters(
        args.task, args.model_type, args.model, name, class_weights
    )

    # Create output directory if it doesn't exist
    if not os.path.exists(args.out_path):
        os.makedirs(args.out_path)

    output_file = os.path.join(args.out_path, args.task + "_hyperparameters.yaml")
    with open(output_file, "w") as file:
        file.write(GENERATED_HEADER)
        yaml.dump(hyperparameters, file, default_flow_style=False, sort_keys=False)

    print("Hyperparameters YAML file saved at " + output_file)
    print("WARNING: This is a template only. It is not sufficient to run any model as-is - fill in "
          "model_parameters and pair it with the separate channel-map and generator YAMLs. Prefer "
          "copying a working config from Models/<Model>/hyperparameters/ when one exists.")


if __name__ == "__main__":
    main()
