from dataset.constants import (
    NO_DAMAGE,
    MINOR_DAMAGE,
    MAJOR_DAMAGE,
    DESTROYED,
    UNCLASSIFIED,
)

EPSG_PREFIX = "EPSG:"
LAT_LON_CRS = EPSG_PREFIX + "4326"

BACKGROUND_CLASS = "background"
PARTIAL = "Partial"
TOTAL = "Total"
ANNOTATION = "Annotation"
ROAD_LINE = "Road Line"

SOURCE_CUSTOM = "custom"

POLYGON_COUNT_PREFIX = "polygon_count_"
PIXEL_COUNT_PREFIX = "pixel_count_"
SAMPLE_GENERATION_TIMING_PREFIX = "sample_timing_"
# Per-worker heap gauges stamped on each sample's metadata (Linux only; see system_telemetry).
WORKER_MEMORY_PREFIX = "worker_memory_"

SAMPLE_METADATA_ATTEMPTS = "attempts"
SAMPLE_METADATA_TIME_SELECT_ORTHO = "select_ortho_time"
SAMPLE_METADATA_TIME_SELECT_BBOX = "select_bbox_time"
SAMPLE_METADATA_TIME_SELECT_SAMPLE = "select_sample_time"
SAMPLE_METADATA_TIME_LOAD_PIXEL_DATA = "load_pixel_data_time"
SAMPLE_METADATA_TIME_DRAW_POLYGON = "draw_polygon_time"
SAMPLE_METADATA_TIME_GENERATE_SAMPLE_POINT = "generate_sample_point_time"
SAMPLE_METADATA_TIME_GET_ANNOTATION = "get_annotation_time"
SAMPLE_METADATA_TIME_VALIDATE_SAMPLE = "validate_sample_time"
SAMPLE_METADATA_TIME_AUGMENTATIONS = "augment_image_time"
SAMPLE_METADATA_TIME_TENSOR_CONVERSION = "convert_tensor_time"
SAMPLE_METADATA_TIME_COMPUTE_TELEMETRY = "compute_telemetry_time"
SAMPLE_METADATA_TIME_TOTAL = "sample_total_time"
SAMPLE_METADATA_GENERATION_FAILED = "failed_sample_generation"
SAMPLE_METADATA_EXCEPTIONS = "exceptions"

SAMPLE_METADATA_POLYGONS_NO_DAMAGE = "polygons_no_damage"
SAMPLE_METADATA_POLYGONS_MINOR_DAMAGE = "polygons_minor_damage"
SAMPLE_METADATA_POLYGONS_MAJOR_DAMAGE = "polygons_major_damage"
SAMPLE_METADATA_POLYGONS_DESTROYED = "polygons_destroyed"
SAMPLE_METADATA_POLYGONS_UNCLASSIFIED = "polygons_unclassified"

SAMPLE_METADATA_PIXELS_NO_DAMAGE = "pixels_no_damage"
SAMPLE_METADATA_PIXELS_MINOR_DAMAGE = "pixels_minor_damage"
SAMPLE_METADATA_PIXELS_MAJOR_DAMAGE = "pixels_major_damage"
SAMPLE_METADATA_PIXELS_DESTROYED = "pixels_destroyed"
SAMPLE_METADATA_PIXELS_UNCLASSIFIED = "pixels_unclassified"

TRAINING_STEP_METADATA_TIME_INTER_STEP = "inter_step_time"
TRAINING_STEP_METADATA_TIME_INTRA_STEP = "intra_step_time"
TRAINING_STEP_METADATA_TIME_INIT = "initialization_time"
TRAINING_STEP_METADATA_TIME_PREPROCESS = "preprocess_time"
TRAINING_STEP_METADATA_TIME_FORWARD = "forward_time"
TRAINING_STEP_METADATA_TIME_LOSS = "loss_time"
TRAINING_STEP_METADATA_TIME_LOG = "log_time"

# BDA Telemetry Lists
BDA_SAMPLE_METADATA_GENERATING_TIMING = [
    SAMPLE_METADATA_TIME_SELECT_ORTHO,
    SAMPLE_METADATA_TIME_GENERATE_SAMPLE_POINT,
    SAMPLE_METADATA_TIME_GET_ANNOTATION,
    SAMPLE_METADATA_TIME_VALIDATE_SAMPLE,
    SAMPLE_METADATA_TIME_SELECT_BBOX,
    SAMPLE_METADATA_TIME_LOAD_PIXEL_DATA,
    SAMPLE_METADATA_TIME_DRAW_POLYGON,
    SAMPLE_METADATA_TIME_AUGMENTATIONS,
    SAMPLE_METADATA_TIME_TENSOR_CONVERSION,
    SAMPLE_METADATA_TIME_TOTAL,
]
BDA_SAMPLE_METADATA_POLYGON_STATS = {
    NO_DAMAGE: SAMPLE_METADATA_POLYGONS_NO_DAMAGE,
    MINOR_DAMAGE: SAMPLE_METADATA_POLYGONS_MINOR_DAMAGE,
    MAJOR_DAMAGE: SAMPLE_METADATA_POLYGONS_MAJOR_DAMAGE,
    DESTROYED: SAMPLE_METADATA_POLYGONS_DESTROYED,
    UNCLASSIFIED: SAMPLE_METADATA_POLYGONS_UNCLASSIFIED,
}
BDA_SAMPLE_METADATA_PIXELS_STATS = {
    NO_DAMAGE: SAMPLE_METADATA_PIXELS_NO_DAMAGE,
    MINOR_DAMAGE: SAMPLE_METADATA_PIXELS_MINOR_DAMAGE,
    MAJOR_DAMAGE: SAMPLE_METADATA_PIXELS_MAJOR_DAMAGE,
    DESTROYED: SAMPLE_METADATA_PIXELS_DESTROYED,
    UNCLASSIFIED: SAMPLE_METADATA_PIXELS_UNCLASSIFIED,
}

# RDA Telemetry Lists
RDA_SAMPLE_METADATA_GENERATING_TIMING = [
    SAMPLE_METADATA_TIME_SELECT_ORTHO,
    SAMPLE_METADATA_TIME_GENERATE_SAMPLE_POINT,
    SAMPLE_METADATA_TIME_GET_ANNOTATION,
    SAMPLE_METADATA_TIME_VALIDATE_SAMPLE,
    SAMPLE_METADATA_TIME_SELECT_BBOX,
    SAMPLE_METADATA_TIME_LOAD_PIXEL_DATA,
    SAMPLE_METADATA_TIME_DRAW_POLYGON,
    SAMPLE_METADATA_TIME_TOTAL,
]
RDA_SAMPLE_METADATA_POLYGON_STATS = [
    SAMPLE_METADATA_POLYGONS_NO_DAMAGE,
    SAMPLE_METADATA_POLYGONS_MINOR_DAMAGE,
    SAMPLE_METADATA_POLYGONS_MAJOR_DAMAGE,
    SAMPLE_METADATA_POLYGONS_DESTROYED,
    SAMPLE_METADATA_POLYGONS_UNCLASSIFIED,
]
RDA_SAMPLE_METADATA_PIXELS_STATS = [
    SAMPLE_METADATA_PIXELS_NO_DAMAGE,
    SAMPLE_METADATA_PIXELS_MINOR_DAMAGE,
    SAMPLE_METADATA_PIXELS_MAJOR_DAMAGE,
    SAMPLE_METADATA_PIXELS_DESTROYED,
    SAMPLE_METADATA_PIXELS_UNCLASSIFIED,
]

TRAINING_STEP_METADATA_TIMING = [
    TRAINING_STEP_METADATA_TIME_INIT,
    TRAINING_STEP_METADATA_TIME_INTER_STEP,
    TRAINING_STEP_METADATA_TIME_INTRA_STEP,
    TRAINING_STEP_METADATA_TIME_PREPROCESS,
    TRAINING_STEP_METADATA_TIME_FORWARD,
    TRAINING_STEP_METADATA_TIME_LOSS,
    TRAINING_STEP_METADATA_TIME_LOG,
]

BDA_IDX_TO_COLOR_MAP = [
    [0, 0, 0],
    [0, 255, 0],
    [255, 255, 0],
    [255, 165, 0],
    [255, 0, 0],
    [128, 0, 128],
]

BDA_INPUT_CATEGORY_ID_MAP = {
    BACKGROUND_CLASS: 0,
    ROAD_LINE: 1,
    MINOR_DAMAGE: 1,
    MAJOR_DAMAGE: 1,
    DESTROYED: 1,
    UNCLASSIFIED: 1,
}

BDA_OUTPUT_CATEGORY_ID_MAP = {
    BACKGROUND_CLASS: 0,
    ROAD_LINE: 1,
    MINOR_DAMAGE: 2,
    MAJOR_DAMAGE: 3,
    DESTROYED: 4,
    UNCLASSIFIED: 5,
}

BDA_QUERY_COLOR_MAP = {
    ROAD_LINE: [128, 128, 128, 255],
    MINOR_DAMAGE: [128, 128, 128, 255],
    MAJOR_DAMAGE: [128, 128, 128, 255],
    DESTROYED: [128, 128, 128, 255],
    UNCLASSIFIED: [128, 128, 128, 255],
}

DESTRUCTION_TOTAL = "Total Destruction"
FLOODING_TOTAL = "Total Flooding"
OBSTRUCTIONS_TOTAL = "Total Obstructions"
OBSTRUCTIONS_PARTIAL = "Partial Obstruction"
FLOODING_PARTIAL = "Partial Flooding"
ROAD_CONDITION_PARTIAL = "Partial Road Condition"

BDA_METRICS = ["AUC_ROC", "F1", "Accuracy", "Precision", "Recall"]
RDA_METRICS = ["F1", "Accuracy", "Precision", "Recall", "IoU"]
PLOT_BAR_OFFSET_FACTOR = 0.1

SATMAE = "SatMAE"
YEAR = "Year"
MONTH = "Month"

# Constants for timestamp offsets for encoders
TIMESTAMP_OFFSET_STRATEGIES = {SATMAE: {YEAR: 2002, MONTH: 1}}
